function p = Param(varargin)
% MWL.Param
% 
% Description:	get a mwlearn parameter
% 
% Syntax:	p = MWL.Param(f1,...,fN)
% 
% In:
% 	fK	- the the Kth parameter field
% 
% Out:
% 	p	- the parameter value
%
% Example:
%	p = GO.Param('color','back');

% ** Do not modify main function. Modifications should be made to the four
% subfunctions "InitializeCIP", "InitializeAngleP", "InitializeWMP" and
% "InitializeAssemblageP".

global strDirBase;

% structs to hold param values
persistent CIP;
persistent AngleP;
persistent WMP;
persistent AssemblageP;


if(nargin == 0)
    p = [];
    return;
end

% choose param struct
strTest = varargin{1};
firstEl = [true false(1,nargin-1)];
cField = varargin(~firstEl);
switch strTest
    case 'ci'
        if(isempty(CIP))
            InitializeCIP;
        end
        P = CIP;
    case 'angle'
        if(isempty(AngleP))
            InitializeAngleP;
        end
        P = AngleP;
    case 'wm'
        if(isempty(WMP))
            InitializeWMP;
        end
        P = WMP;
    case 'assemblage'
        if(isempty(AssemblageP))
            InitializeAssemblageP;
        end
        P = AssemblageP;
    otherwise
        p = [];
        return;
end

% get paramter value
p = P;
for k=1:numel(cField)
    field = cField{k};
    switch class(field)
        case 'char'
            if isfield(p, field)
                p = p.(field);
            else
                p = [];
                return;
            end
        otherwise
            if iscell(p)    % if we're indexing into a cell
                p = p{field};
            else
                p = [];
                return;
            end
    end
end
    
%-----------------------------------------------------------------------%
    function InitializeCIP
        %--experiment parameters---------------------------------   
        CIP.numTrial = 30;
        CIP.numPractice = 2;
        CIP.dLevelPractice = 0.05;        
        CIP.time = struct(...
            'prompt'    , 2000, ...
            'construct' , 6000, ...
            'test'      , 2500, ...
            'pause'     , 0,    ...
            'feedback'  , 2000, ...
            'prepare'   , 0     ...
            );
        % image parts
        CIP.partsDir = DirAppend(strDirBase, 'images', 'ci');
        CIP.partsExt = 'png';
        CIP.numParts = numel(dir(PathUnsplit(CIP.partsDir, '*', CIP.partsExt)));
        
        CIP.color = struct(...
            'back', 'gray' , ...
            'fore', 'black', ...
            'text', 'black'  ...
            );
        %--sizes------------------------------------------------
        % Image sizes in visual angle
        CIP.imSize = struct(... 
            'part', 4, ...
            'figure'  , 8);            
        % width of spacer as fraction of part side
        CIP.spacerFrac = 1/2;
        % with of spacer in VA
        CIP.spacerWidth = floor(CIP.imSize.part*CIP.spacerFrac);
        % ** continuation of imSize **
        CIP.imSize.partStrip = 4*CIP.imSize.part + 3*CIP.spacerWidth;
        
        % psychocurve parameters
        CIP.psychocurve = struct(       ...
            'targetFracCorrect', 2/3,   ...
            'baselineFracCorrect', 1/4, ...
            'xstep', 0.01,              ...
            'start_t', 0.9            ...
            );
        % example figure
        CIP.example = horzcat([5; 3; 4; 9], ...
                              [5; 3; 6; 9], ...
                              [2; 3; 4; 9], ...
                              [5; 3; 4; 7]);
    end

%------------------------------------------------------------------------%
    function InitializeAngleP
        %--experiment parameters--------------------------------------
        AngleP.numTrial = 40;
        % practice
        AngleP.numPractice = 2;
        AngleP.minPracticeAngle = 30;
        AngleP.refAngles = [90 60 45 30 20 15 10 8 6 5 4 3 2 1];
        AngleP.maxRotation = 90;
        % instructions
        AngleP.sample = struct( ...
            'image', 44, ...
            'startAngle', 110, ...
            'degRotCorr', -30, ...
            'degRotIncorr', -20, ...
            'correctPos' , 'left', ...
            'color', 'black' ...
            );
        % psychocurve parameters
        AngleP.psychocurve = struct(       ...
            'targetFracCorrect', 3/4,   ...
            'baselineFracCorrect', 1/2, ...
            'xmin', 1,                 ...
            'xmax', 90,                 ...
            'xstep', 1,              ...
            'start_t', 60         ...
            );
        AngleP.image = struct(...
            'dir', DirAppend(strDirBase, 'images', 'rotate','png'),...
            'ext', 'png'...
            );
        AngleP.image.num = numel(dir(PathUnsplit(AngleP.image.dir, '*', AngleP.image.ext)));
        AngleP.color = MWL.Angle.GetGoodColors;
        AngleP.time = struct(...
            'prompt'    , 2000, ...
            'rotate'    , 4000, ...
            'test'      , 500,  ...
            'response'  , 1500, ...
            'pause'     , 0,    ...
            'feedback'  , 2000, ...
            'prepare'   , 0     ...
            );
    end
%------------------------------------------------------------------------%
    function InitializeWMP
        WMP.run = struct(...
            'mu', false, ...
            'os', false, ...
            'ss', true, ...
            'sstm', true...
            );
        WMP.mu = struct(...
            'numPractice', 2, ... 
            'numTrial', 15 ...
            );
        WMP.os = struct(...
            'listLength', 4:8, ...
            'trialsPerCond', 3 ...
            );
        WMP.os.numTrial = numel(WMP.os.listLength).*WMP.os.trialsPerCond;
        WMP.ss = struct(...
            'trialsPerCond', 3, ...
            'version', 'easy' ...
            );
        WMP.ss.listLength = conditional(strcmp(WMP.ss.version,'hard'),...
            3:7, ... if hard
            4:8  ... if easy
        );
        % practice list length
        WMP.ss.pll = conditional(strcmp(WMP.ss.version,'hard'),...
            [2 3 4],... if hard
            [3 4 5]...  if easy
            );
        WMP.ss.numTrial = numel(WMP.os.listLength).*WMP.os.trialsPerCond;
        WMP.sstm = struct(...
            'numTrial', 30);
    
    end
%------------------------------------------------------------------------%
    function InitializeAssemblageP
		AssemblageP.numPractice = 3;
		AssemblageP.numTrial = 30;
		AssemblageP.dLevelPractice = 1:3; % range of dLevels to use for practice
		AssemblageP.dLevel = 1:10; % range of dLevels to use for the experiment
		% psychocurve parameters
		AssemblageP.psychocurve = struct(       ...
			'targetFracCorrect', 3/4,   ...
			'baselineFracCorrect', 1/4, ...
			'xstep',   1/range(AssemblageP.dLevel),         ...
			'start_t', 0.9        ...
			);
		AssemblageP.time = struct(...
			'perWord', 300, ...
			'perLine', 500, ...
			'test', 2500, ...
			'pause', 0, ...
			'feedback', 2000, ...
			'prepare',  0 ...
			);
		AssemblageP.size	= struct(...
			'figure'		, 8	, ...
			'offset'		, 10 ...
			);
    end
%-----------------------------------------------------------------------%
end
